"""Built-in Deterministic Remediation Knowledge Base for ARC CLOUD Rules."""
from __future__ import annotations

from typing import Any, Dict

RULE_KNOWLEDGE_BASE: Dict[str, Dict[str, Any]] = {
    # Code Quality (ARC001 - ARC011)
    "ARC001": {
        "title": "Excessive Function Complexity",
        "engine": "code_quality",
        "root_cause": "Function contains too many branching control statements (if/elif/for/while/try).",
        "impact": "Code becomes exceedingly difficult to test, maintain, reason about, and prone to edge-case bugs.",
        "risk_if_not_fixed": "High regression rate during refactoring; unmaintainable unit tests.",
        "remediation_steps": [
            "Decompose the function into smaller, single-responsibility helper functions.",
            "Use early returns/guard clauses to reduce nested branching.",
            "Replace complex conditional branches with a dictionary mapping, strategy pattern, or polymorphism.",
        ],
        "code_before": "def process(x):\n    if x > 0:\n        if x < 10:\n            for i in range(x):\n                if i % 2 == 0:\n                    ...",
        "code_after": "def process(x):\n    if not (0 < x < 10):\n        return\n    _process_even_items(x)\n\ndef _process_even_items(limit):\n    for i in range(limit):\n        if i % 2 == 0:\n            ...",
        "side_effects": "Call stack depth may slightly increase; ensure parameter scoping between helper functions is clean.",
        "suggested_test": "Write isolated unit tests for each new helper function with edge boundary inputs.",
    },
    "ARC002": {
        "title": "Long Function",
        "engine": "code_quality",
        "root_cause": "Function exceeds recommended line threshold (e.g. > 50 lines).",
        "impact": "Violates single-responsibility principle; cognitive overload for readers.",
        "risk_if_not_fixed": "Difficulty locating logic errors; high likelihood of merge conflicts.",
        "remediation_steps": [
            "Identify distinct phases (parsing, validation, execution, formatting).",
            "Extract each phase into focused subroutines or dedicated classes.",
        ],
        "code_before": "def do_everything():\n    # 100 lines of mixed validation, DB queries, and response formatting\n    pass",
        "code_after": "def do_everything():\n    data = validate_input()\n    result = execute_query(data)\n    return format_response(result)",
        "side_effects": "Minimal if subroutines are pure functions.",
        "suggested_test": "Verify end-to-end integration with existing test suite before and after extraction.",
    },
    "ARC003": {
        "title": "Deeply Nested Control Flow",
        "engine": "code_quality",
        "root_cause": "Excessive indentation levels (e.g. > 4 levels of nested loops and conditionals).",
        "impact": "High mental tracking cost; hard to verify all condition combinations.",
        "risk_if_not_fixed": "Hidden bugs under deep edge conditions.",
        "remediation_steps": [
            "Use guard clauses (return early).",
            "Invert conditions to exit fast.",
            "Extract inner loop bodies into standalone functions.",
        ],
        "code_before": "if valid:\n    for item in items:\n        if item.ready:\n            while retries > 0:\n                ...",
        "code_after": "if not valid:\n    return\nfor item in items:\n    _process_ready_item(item)",
        "side_effects": "None; purely improves readability and execution path clarity.",
        "suggested_test": "Test early return branches to ensure invalid states exit immediately.",
    },
    "ARC004": {
        "title": "Duplicate Code",
        "engine": "code_quality",
        "root_cause": "Identical or near-identical multi-line blocks replicated across files or modules.",
        "impact": "Violates DRY (Don't Repeat Yourself).",
        "risk_if_not_fixed": "Fixing a bug in one instance leaves the remaining replicas vulnerable (copy-paste bugs).",
        "remediation_steps": [
            "Extract common logic into a shared utility function, module, or base class.",
            "Import and call the shared function in both locations.",
        ],
        "code_before": "# File A and File B both implement the same 10-line calculation",
        "code_after": "# utils/math.py\ndef compute_metric(...):\n    ...\n# File A & B: from utils.math import compute_metric",
        "side_effects": "Changes to the shared function will affect all callers.",
        "suggested_test": "Run all tests for both caller modules after extracting shared utility.",
    },
    "ARC006": {
        "title": "Large Class (God Object)",
        "engine": "code_quality",
        "root_cause": "Class has too many methods or lines of code.",
        "impact": "Violates Single Responsibility Principle; high coupling.",
        "risk_if_not_fixed": "Fragile architecture; changing one feature breaks unrelated features in the class.",
        "remediation_steps": [
            "Split responsibilities into distinct collaborator classes.",
            "Use composition over inheritance.",
        ],
        "code_before": "class OrderManager:\n    # Handles payments, shipping, user notification, database persistence",
        "code_after": "class OrderManager:\n    def __init__(self, payment_svc, shipping_svc, notifier): ...",
        "side_effects": "Requires updating object instantiation or dependency injection container.",
        "suggested_test": "Unit test each decomposed service with mock collaborators.",
    },
    "ARC007": {
        "title": "Excessive Parameter Count",
        "engine": "code_quality",
        "root_cause": "Function accepts too many arguments (e.g. > 5).",
        "impact": "Easy to pass arguments in wrong order; brittle call signatures.",
        "risk_if_not_fixed": "API churn and silent parameter swapping bugs.",
        "remediation_steps": [
            "Group related parameters into a dataclass, Pydantic model, or options dict.",
            "Use keyword-only arguments where appropriate.",
        ],
        "code_before": "def create_user(name, email, phone, address, city, state, zip_code, role): ...",
        "code_after": "@dataclass\nclass UserProfile:\n    ...\ndef create_user(profile: UserProfile): ...",
        "side_effects": "Call sites must be updated to pass the parameter object.",
        "suggested_test": "Verify serialization and deserialization of the new options/dataclass object.",
    },
    "ARC011": {
        "title": "Excessive File Size",
        "engine": "code_quality",
        "root_cause": "Source file exceeds recommended line limit (e.g. > 500 lines).",
        "impact": "Difficult navigation, merge conflicts, poor modularity.",
        "risk_if_not_fixed": "Monolithic architecture drift.",
        "remediation_steps": [
            "Decompose into a Python package with smaller submodules.",
            "Separate types, interfaces, business logic, and adapters into dedicated files.",
        ],
        "code_before": "big_module.py (1200 lines)",
        "code_after": "big_module/\n  __init__.py\n  models.py\n  service.py\n  handlers.py",
        "side_effects": "Import statements in external modules may need updating (or re-exported in __init__.py).",
        "suggested_test": "Verify package imports remain backward-compatible.",
    },

    # Security (ARC-SEC-*)
    "ARC-SEC-002": {
        "title": "SQL Injection Risk",
        "engine": "security",
        "root_cause": "SQL statement formatted using dynamic string concatenation, f-string, or string format.",
        "impact": "Attackers can manipulate SQL query syntax to bypass authentication, read sensitive records, or drop tables.",
        "risk_if_not_fixed": "Complete database compromise and data exfiltration.",
        "remediation_steps": [
            "Replace string formatting with parameterized queries / prepared statements.",
            "Use ORM query builders (e.g. SQLAlchemy, Django ORM).",
        ],
        "code_before": 'cursor.execute(f"SELECT * FROM users WHERE id = \'{user_id}\'")',
        "code_after": 'cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))',
        "side_effects": "None; performance usually improves due to query plan caching in RDBMS.",
        "suggested_test": "Provide payload with single quotes, e.g. `' OR '1'='1`, and verify safe parameterization without SQL error.",
    },
    "ARC-SEC-003": {
        "title": "Command Injection Risk (shell=True)",
        "engine": "security",
        "root_cause": "Invoking system commands through subprocess with shell=True and unescaped arguments.",
        "impact": "Attackers can chain shell commands (via `;`, `&&`, `|`) to execute arbitrary commands on the server.",
        "risk_if_not_fixed": "Remote Code Execution (RCE), container escape, host takeover.",
        "remediation_steps": [
            "Pass arguments as a list with shell=False (the default).",
            "Use shlex.quote() if shell mode is strictly unavoidable.",
        ],
        "code_before": 'subprocess.run(f"echo {user_input}", shell=True)',
        "code_after": 'subprocess.run(["echo", user_input], shell=False, check=True)',
        "side_effects": "Shell built-ins (like `cd` or shell redirection `>`) cannot be used directly with shell=False.",
        "suggested_test": "Pass input containing `; rm -rf /` or `$(id)` and verify it is treated as a literal argument string.",
    },
    "ARC-SEC-005": {
        "title": "Unsafe Dynamic Code Execution (eval / exec)",
        "engine": "security",
        "root_cause": "Calling eval() or exec() on runtime string data.",
        "impact": "Executes arbitrary Python code within the host runtime environment.",
        "risk_if_not_fixed": "Arbitrary code execution leading to full process takeover.",
        "remediation_steps": [
            "Use ast.literal_eval() for safely parsing Python literals (dicts, lists, numbers).",
            "Use json.loads() for structured JSON inputs.",
            "Refactor code to use explicit dispatch tables or serializers.",
        ],
        "code_before": "user_data = eval(request_body)",
        "code_after": "import json\nuser_data = json.loads(request_body)",
        "side_effects": "ast.literal_eval will not evaluate arbitrary expressions (which is intentional for security).",
        "suggested_test": "Test with valid JSON/literal payload and verify malicious syntax throws a parse error.",
    },
    "ARC-SEC-007": {
        "title": "Broken or Weak Cryptographic Hash (MD5 / SHA1)",
        "engine": "security",
        "root_cause": "Using obsolete hash algorithms like MD5 or SHA1 for security-sensitive purposes.",
        "impact": "Vulnerable to collision and pre-image attacks.",
        "risk_if_not_fixed": "Forged signatures, tampered payloads, credential recovery.",
        "remediation_steps": [
            "Use SHA-256 (hashlib.sha256()) or SHA-3 for general hashing.",
            "Use bcrypt, Argon2, or PBKDF2 for password hashing.",
        ],
        "code_before": "token_hash = hashlib.md5(data.encode()).hexdigest()",
        "code_after": "token_hash = hashlib.sha256(data.encode()).hexdigest()",
        "side_effects": "Hash digest length increases (32 chars for MD5 -> 64 chars for SHA-256); verify DB column size.",
        "suggested_test": "Verify hashing and verification of valid payloads with the new algorithm.",
    },
    "ARC-SEC-008": {
        "title": "Insecure HTTP Protocol Usage",
        "engine": "security",
        "root_cause": "Targeting endpoints or assets via plaintext http:// instead of https://.",
        "impact": "Traffic is sent unencrypted over network; vulnerable to Man-In-The-Middle (MITM) eavesdropping and tampering.",
        "risk_if_not_fixed": "Session hijacking, credential theft, data tampering.",
        "remediation_steps": [
            "Upgrade URL scheme to https://.",
            "Ensure TLS certificates are valid on the target endpoint.",
        ],
        "code_before": 'api_url = "http" + "://api.example.com/v1/auth"',
        "code_after": 'api_url = "https://api.example.com/v1/auth"',
        "side_effects": "Target server must support HTTPS/TLS.",
        "suggested_test": "Send test request to ensure target server responds with 200 OK over HTTPS.",
    },

    # Secrets (ARC-SECR-*)
    "ARC-SECR-001": {
        "title": "Hardcoded AWS Access Key",
        "engine": "secrets",
        "root_cause": "AWS Access Key ID (AKIA...) detected in source code.",
        "impact": "Anyone with access to the source repository or build artifacts can access AWS cloud resources.",
        "risk_if_not_fixed": "Cloud resource takeover, cryptomining abuse, massive billing surprises, data leakage.",
        "remediation_steps": [
            "Immediately rotate and invalidate the exposed key in the AWS IAM Console.",
            "Read credentials from environment variables (e.g. AWS_ACCESS_KEY_ID) or AWS IAM Roles/Profiles.",
            "Add .env and credential files to .gitignore.",
        ],
        "code_before": 'AWS_KEY = "AKIA" + "_EXAMPLE_KEY_12345"',
        "code_after": 'import os\nAWS_KEY = os.environ.get("AWS_ACCESS_KEY_ID")',
        "side_effects": "Deployment environments must be provisioned with environment variables or instance profiles.",
        "suggested_test": "Verify application boots successfully with environment variable populated.",
    },
    "ARC-SECR-002": {
        "title": "Hardcoded GitHub Personal Access Token",
        "engine": "secrets",
        "root_cause": "GitHub token (ghp_... or github_pat_...) committed in source code.",
        "impact": "Unauthorized access to private GitHub repositories, packages, and organization settings.",
        "risk_if_not_fixed": "Source code exfiltration, supply chain injection via git commit.",
        "remediation_steps": [
            "Revoke token immediately in GitHub Settings -> Developer Settings.",
            "Use GitHub Actions secrets or environment variables for token injection.",
        ],
        "code_before": 'GITHUB_TOKEN = "ghp_xxxxxxxxxxxxxxxxxxxx"',
        "code_after": 'import os\nGITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")',
        "side_effects": "Local developer workflows require setting local .env or secret manager.",
        "suggested_test": "Run git status and CI workflow to verify secret injection via secrets context.",
    },
    "ARC-SECR-003": {
        "title": "Private Key Committed in Repository",
        "engine": "secrets",
        "root_cause": "RSA/EC/DSA/OPENSSH private key block present in file.",
        "impact": "Compromised SSH access, TLS communication, or cryptographic signing.",
        "risk_if_not_fixed": "Total identity spoofing and remote server access.",
        "remediation_steps": [
            "Revoke and regenerate key pair immediately.",
            "Store private key in secrets vault (HashiCorp Vault, AWS Secrets Manager, GCP Secret Manager).",
            "Remove key file from git history using git filter-repo if committed previously.",
        ],
        "code_before": "-----BEGIN RSA PRIVATE KEY-----\nMIIE...",
        "code_after": "# Stored in vault, injected via secret path or env var",
        "side_effects": "Servers must have authorized_keys updated with the new public key.",
        "suggested_test": "Verify connection with newly rotated key from secure storage.",
    },

    # Reliability (ARC-REL-*)
    "ARC-REL-001": {
        "title": "Suppressed Broad Exception (except Exception: pass)",
        "engine": "reliability",
        "root_cause": "Catching all exceptions and silently passing without logging or re-raising.",
        "impact": "Masks unexpected bugs, fatal conditions, memory errors, or system errors.",
        "risk_if_not_fixed": "Silent data corruption, impossible-to-diagnose production outages.",
        "remediation_steps": [
            "Catch specific exception types (e.g. ValueError, FileNotFoundError).",
            "At minimum, log the exception traceback using logging.exception().",
        ],
        "code_before": "try:\n    perform_action()\nexcept Exception:\n    pass",
        "code_after": "import logging\ntry:\n    perform_action()\nexcept SpecificError as exc:\n    logging.warning(\"Action skipped due to expected condition: %s\", exc)",
        "side_effects": "Previously hidden errors may now surface, allowing them to be properly resolved.",
        "suggested_test": "Trigger an erroneous condition and assert that it logs appropriately or raises expected handled status.",
    },
    "ARC-REL-002": {
        "title": "Unclosed File Resource",
        "engine": "reliability",
        "root_cause": "Calling open() without a 'with' context manager.",
        "impact": "File descriptors leak if an error occurs before explicit close().",
        "risk_if_not_fixed": "OS error: 'Too many open files', process crash.",
        "remediation_steps": [
            "Always wrap file I/O in a `with open(...) as f:` context manager block.",
        ],
        "code_before": "f = open('data.txt', 'r')\ncontent = f.read()",
        "code_after": "with open('data.txt', 'r', encoding='utf-8') as f:\n    content = f.read()",
        "side_effects": "None; guaranteed deterministic cleanup.",
        "suggested_test": "Verify file descriptor count does not grow during high-iteration I/O loops.",
    },

    # Dependencies (ARC-DEP-*)
    "ARC-DEP-001": {
        "title": "Unpinned or Wildcard Dependency Version",
        "engine": "dependencies",
        "root_cause": "Specifying dependency with `*` or unbounded ranges.",
        "impact": "Builds are non-reproducible; upstream breaking changes break production unexpectedly.",
        "risk_if_not_fixed": "Supply chain compromise via dependency confusion or unexpected breaking releases.",
        "remediation_steps": [
            "Pin dependencies to exact or compatible versions (e.g. `package>=1.2.0,<2.0.0` or `^1.2.0`).",
            "Commit lockfiles (`poetry.lock`, `package-lock.json`).",
        ],
        "code_before": '"requests": "*"',
        "code_after": '"requests": "^2.31.0"',
        "side_effects": "Requires intentional upgrades when taking dependency updates.",
        "suggested_test": "Run clean install in isolated environment to verify dependency resolution.",
    },

    # Architecture (ARC-ARCH-*)
    "ARC-ARCH-001": {
        "title": "Circular Dependency Detected",
        "engine": "architecture",
        "root_cause": "Module A imports Module B, and Module B directly or indirectly imports Module A.",
        "impact": "ImportError at startup, tight coupling, impossible unit testing in isolation.",
        "risk_if_not_fixed": "Fragile architecture; inability to refactor or reuse modules.",
        "remediation_steps": [
            "Extract shared interfaces, types, or data structures into a separate leaf module.",
            "Use dependency inversion: pass dependencies at runtime rather than importing across layers.",
        ],
        "code_before": "# a.py: import b\n# b.py: import a",
        "code_after": "# common.py: defines SharedModel\n# a.py: import common\n# b.py: import common",
        "side_effects": "May require adjusting import paths in consuming files.",
        "suggested_test": "Test importing Module A and Module B independently in a fresh Python session.",
    },

    # Performance (ARC-PERF-*)
    "ARC-PERF-001": {
        "title": "High Algorithmic Complexity (O(n^3)+ Nested Loops)",
        "engine": "performance",
        "root_cause": "3 or more levels of nested loops iterating over collections.",
        "impact": "Execution time scales cubically or worse with input size.",
        "risk_if_not_fixed": "CPU spikes, API timeouts, denial-of-service on larger datasets.",
        "remediation_steps": [
            "Pre-index the inner collection into a dictionary or set for O(1) lookups.",
            "Use vectorized operations (e.g. NumPy/Pandas) or database joins.",
        ],
        "code_before": "for a in list_a:\n    for b in list_b:\n        for c in list_c:\n            if a.id == b.a_id and b.id == c.b_id: ...",
        "code_after": "lookup = {b.a_id: b for b in list_b}\n# Reduced to single or double linear pass",
        "side_effects": "Trades slight additional memory for massive CPU time reduction.",
        "suggested_test": "Benchmark execution time with 10, 100, and 1,000 items.",
    },
    "ARC-PERF-002": {
        "title": "Regex Compilation Inside Loop",
        "engine": "performance",
        "root_cause": "re.compile() or re.match(pattern, ...) called inside a repeating loop.",
        "impact": "Repeated regex parsing and bytecode generation on every iteration.",
        "risk_if_not_fixed": "Significant latency overhead in tight loops.",
        "remediation_steps": [
            "Compile regular expressions once at module level as constants.",
        ],
        "code_before": "for line in lines:\n    if re.search(r'\\d+', line): ...",
        "code_after": "NUM_PATTERN = re.compile(r'\\d+')\nfor line in lines:\n    if NUM_PATTERN.search(line): ...",
        "side_effects": "None; strictly improves loop performance.",
        "suggested_test": "Benchmark loop time with 10,000 items.",
    },

    # Testing (ARC-TEST-*)
    "ARC-TEST-001": {
        "title": "Critical Core Module Lacks Corresponding Unit Tests",
        "engine": "testing",
        "root_cause": "High-complexity core or business logic file has no matching test module in tests/ directory.",
        "impact": "Changes to critical logic cannot be validated automatically.",
        "risk_if_not_fixed": "Production regressions go undetected until deployed.",
        "remediation_steps": [
            "Create a new test file in tests/ targeting this module.",
            "Add tests covering happy path, edge cases, and error handling.",
        ],
        "code_before": "# core/calculator.py exists, but tests/test_calculator.py does not",
        "code_after": "# tests/test_calculator.py\ndef test_calculator_basic(): ...",
        "side_effects": "Increases CI run time marginally.",
        "suggested_test": "Run pytest tests/test_module.py to verify test execution.",
    },

    # AI Risk (ARC-AIRISK-*)
    "ARC-AIRISK-001": {
        "title": "Elevated AI/Composite Engineering Risk Detected",
        "engine": "ai_risk",
        "root_cause": "Multiple compounding risks co-occur (e.g. high complexity + security findings + missing tests).",
        "impact": "Exponentially increases probability of major system defect or exploit.",
        "risk_if_not_fixed": "Compounding system failure where a security hole in un-tested code is exploited.",
        "remediation_steps": [
            "Address the highest severity security and reliability findings first.",
            "Establish unit tests around the volatile modules.",
            "Refactor cyclomatic complexity into isolated tested components.",
        ],
        "code_before": "Unmitigated compounding risk profile",
        "code_after": "Targeted remediation of root vulnerabilities and added test coverage",
        "side_effects": "Improves overall engineering health score.",
        "suggested_test": "Run `arc scan` to confirm risk score drops below warning threshold.",
    },
}
